const DEFAULT_CHANNEL = process.env.DEFAULT_CHANNEL;
const WS_URL_IO = process.env.WS_URL_IO;
const WS_URL_MESSAGE = process.env.WS_URL_MESSAGE;
const WS_URL_DIRECT_MESSAGE = process.env.WS_URL_DIRECT_MESSAGE;

export { DEFAULT_CHANNEL, WS_URL_IO, WS_URL_MESSAGE, WS_URL_DIRECT_MESSAGE };
